### ISSUE TITLE
Webpage render gapminder issue

### ISSUE THREAD

**Issue by pandubalraj** [vizabi/vizabi#2822]
Hi,

I am trying to render the gapminder in the webpage as given in 
https://vizabi.org/tutorials/2017/04/03/show-your-data/

When I try to copy paste the html code as given in the above link 

I am getting error as 
Uncaught **ReferenceError: Vizabi is not defined**
    at Object.<anonymous> (bubblechart.js:1)
    at t (bubblechart.js:1)
    at Object.<anonymous> (bubblechart.js:1)
    at t (bubblechart.js:1)
    at Object.<anonymous> (bubblechart.js:1)
    at t (bubblechart.js:1)
    at Object.<anonymous> (bubblechart.js:1)
    at t (bubblechart.js:1)
    at bubblechart.js:1
    at bubblechart.js:1

Am I doing anything wrong. Please advice
Thanks in Advance

**Comment by angieskazka** [comment]
hi @pandubalraj! 
if i understand correctly you are trying to use the script from the bottom of the page

the error `Vizabi is not defined` could happen because the line
`<script src="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/vizabi.js"></script>`
was missing

also when i checked it, the translation file couldn't be located, so i fixed that

test: 
go to https://vizabi.org/tutorials/2017/04/03/show-your-data/
scroll all the way down
copy the code snippet
open https://jsfiddle.net/
paste the code in HTML part
press run
see it works

![image](https://user-images.githubusercontent.com/3648190/33165412-02d6acb6-d037-11e7-88ff-387e6f88c89e.png)


does this solve your problem? : )

**Comment by cdemest** [comment]
I have a similar issue when viewing: https://vizabi.org/tutorials/2017/04/03/show-your-data/
In the "interactive example", I can only see a "spinner" spinning and not the actual chart (I have waited for several minutes for it to load but it didn't). 
I have tried visiting the page with different browsers and the same problem persists. 
I have also tested using the code snippet and https://jsfiddle.net/, but again only the "spinner" appears and nothing else.

**Comment by jane-taleika** [comment]
Similar issue: all /s3-eu-west-1.amazonaws.com scripts are responding with 'Access Denied'

**Comment by paolosaudin** [comment]
Same issue, Access Denied...
